- name: Add metrics server repo
  ansible.builtin.command:
    cmd: helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

- name: Install metrics server
  ansible.builtin.shell:
    cmd: |
      helm install \
        metrics-server metrics-server/metrics-server \
        --namespace kube-system \
        --set args={--kubelet-insecure-tls} \
        --set replicas=3
