- name: Add cilium repo
  ansible.builtin.command:
    cmd: helm repo add cilium https://helm.cilium.io/

- name: Install cilium
  ansible.builtin.shell:
    cmd: |
      helm install cilium cilium/cilium \
        --version 1.16.6 \
        --namespace kube-system \
        --set ipam.mode=kubernetes \
        --set kubeProxyReplacement=true \
        --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
        --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
        --set cgroup.autoMount.enabled=false \
        --set cgroup.hostRoot=/sys/fs/cgroup \
        --set k8sServiceHost=localhost \
        --set k8sServicePort=7445
  register: cilium_install
  changed_when: cilium_install.rc == 0
  failed_when: cilium_install.rc != 0 and 'already exists' not in cilium_install.stderr
