---
- name: Apply config to first worker
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure --nodes {{ worker_1 }} --file {{ config_directory }}/worker.yaml
  changed_when: true

- name: Apply config to second worker
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure --nodes {{ worker_2 }} --file {{ config_directory }}/worker.yaml
  changed_when: true

- name: Apply config to second worker
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure --nodes {{ worker_3 }} --file {{ config_directory }}/worker.yaml
  changed_when: true