---

stages:
  - build
  - lint

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t registry.gitlab.com/daisukebtw/playbooks .
    - docker push registry.gitlab.com/daisukebtw/playbooks

lint:
  image: registry.gitlab.com/daisukebtw/playbooks
  stage: lint
  variables:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    ANSIBLE_CONFIG: ./ansible.cfg
  script:
    - ansible-lint -vvv ./*.yml
