---

stages:
  - lint

image: registry.gitlab.com/daisukebtw/playbooks

build_job:
  stage: lint
  variables:
    LANG: en_US.UTF-8
#    LC_ALL: en_US.UTF-8
    ANSIBLE_CONFIG: /etc/ansible/ansible.cfg
  script:
    - for i in $( ls | grep *.yml ); do ansible-lint $i ; done
