---

- name: Initial setup Ubuntu 22.04
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Update apt repositories and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Remove snapd
      import_tasks: import_tasks/snapd-remove.yml

    - name: Install packages
      apt:
        name:
          - curl
          - git
          - wget
        state: present

    - name: Deny password authentication
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        replace: 'PasswordAuthentication no'
      notify:
        - Reload sshd

  handlers:
    - name: Reload sshd
      systemd_service:
        name: sshd
        state: restarted
