---

- name: Initial setup Ubuntu 22.04
  hosts: all
  gather_facts: false
  become: yes

  vars_prompt:
    - name: new_root_password_encrypted
      prompt: Please enter the new root password
      private: true
      encrypt: sha512_crypt
      confirm: true
      unsafe: true

  tasks:
    - name: Change root password
      user:
        name: root
        password: "{{ new_root_password_encrypted }}"

    - name: Update apt repositories and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Remove snapd
      import_tasks: snapd-remove.yml

    - name: Install packages
      apt:
        name:
          - curl
          - git
          - wget
        state: present

    - name: Add multiple authorized keys
      ansible.posix.authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/bezdar-pc
        - public_keys/bezdar-laptop

    - name: Allow root login
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin prohibit-password'
        replace: 'PermitRootLogin yes'
      notify:
        - Reload sshd

    - name: Deny password authentication
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        replace: 'PasswordAuthentication no'
      notify:
        - Reload sshd

  handlers:
    - name: Reload sshd
      systemd_service:
        name: sshd
        state: restarted
