---

- name: Remove snapd from ubuntu server 22.04
  become: true
  hosts: all
  gather_facts: false

  tasks:
    - name: Remove snapd apps
      community.general.snap:
        name: "{{ item }}"
        state: absent
      loop:
        - lxd
        - core20
        - snapd

    - name: Remove snap directories
      ansible.builtin.command: rm -rf /snap ~/snap

    - name: Mask snap services
      ansible.builtin.systemd_service:
        name: snapd
        enabled: false
        masked: yes
        state: stopped

    - name: Remove snapd
      ansible.builtin.apt:
        name: snapd
        state: absent
        purge: yes
