---

- name: Remove snapd from ubuntu server 22.04
  become: true
  hosts: all
  gather_facts: false

  tasks:
    - name: Remove snapd apps
      community.general.snap:
        name: "{{ item }}"
        state: absent
      loop:
        - lxd
        - core20
        - snapd

    - name: Remove snap directories
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - /snap
        - /root/snap

    - name: Mask snap services
      systemd_service:
        name: snapd
        enabled: false
        masked: yes
        state: stopped

    - name: Remove snapd
      apt:
        name: snapd
        state: absent
        purge: yes
