---

- name: Update apt repositories and upgrade
  hosts: all
  gather_facts: false

  tasks:
    - name: Update apt repositories and upgrade
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
