---

# to define host use next command to launch playbook "ansible-playbook playbook.yml -e target_host=[IP]" 
- name: Setup Zabbix-Agent on Debian 12 AMD64 host
  hosts: all

  vars:
    zabbix_server: 10.11.0.50

  tasks:
    - name: Download Zabbix-Agent package
      get_url: 
        url: https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb
        dest: /tmp/zabbix-release_latest+debian12_all.deb
        mode: 744
      when: ansible_architecture == "x86_64"
      notify: Update repositories

    - name: Download Zabbix-Agent package
      get_url: 
        url: https://repo.zabbix.com/zabbix/7.0/debian-arm64/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb
        dest: /tmp/zabbix-release_latest+debian12_all.deb
        mode: 744
      when: ansible_architecture == "aarch64"
      notify: Update repositories

    - name: Depackage Zabbix-Agent
      apt:
        deb: /tmp/zabbix-release_latest+debian12_all.deb

    - name: Install Zabbix-Agent package
      apt:
        name: zabbix-agent
        state: present
      notify:
        - Reload Zabbix-Agent
    
    - name: Replace Server IP in Zabbix-Agent config
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server=127.0.0.1'
        replace: 'Server={{ zabbix_server }}'

    - name: Replace ServerActive IP in Zabbix-Agent config
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive=127.0.0.1'
        replace: 'ServerActive={{ zabbix_server }}'

    - name: Replace ServerActive IP in Zabbix-Agent config
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname=Zabbix server'
        replace: 'Hostname={{ ansible_hostname }}'
      notify:
        - Reload Zabbix-Agent

  handlers:
    - name: Reload Zabbix-Agent
      systemd_service:
        name: zabbix-agent
        state: restarted
    
    - name: Update repositories
      apt:
        update_cache: yes