- name: Install helm
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: Install talosctl
  ansible.builtin.shell:
    cmd: curl -sL https://talos.dev/install | sh

- name: Install kubectl
  ansible.builtin.shell:
    cmd: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Install python3 and pip
  apt:
    name:
      - python3-pip
      - python3
    state: present
    update_cache: yes

- name: Install required Python packages
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
    state: present
