# For Semaphore
- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Install helm
  ansible.builtin.command:
    cmd: |
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      chmod 700 get_helm.sh
      ./get_helm.sh

- name: Install talosctl
  ansible.builtin.command:
    cmd: curl -sL https://talos.dev/install | sh

- name: Install kubectl
  ansible.builtin.command:
    cmd: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    
- name: Install python3
  ansible.builtin.command:
    cmd: |
      apt install python3-pip
      pip3 install openshift pyyaml kubernetes
