machine:
  network:
    interfaces:
    - interface: enp6s18
      dhcp: true
      vip:
        ip: 10.10.30.50
    nameservers:
      - 10.10.30.1
      - 1.1.1.1
  install:
    disk: /dev/sda
  time:
    servers:
      - time.cloudflare.com
cluster:
  allowSchedulingOnControlPlanes: true
  network:
    cni:
      name: none
  proxy:
    disabled: true