---

# to define host use next command to launch playbook "ansible-playbook playbook.yml -e target_host=[IP]" 
- name: Install Proxmox on Raspberry PI
  hosts: all
  become: true
  gather_facts: false

  vars_prompt:
    - name: new_root_password_encrypted
      prompt: Please enter the new root password
      private: true
      encrypt: sha512_crypt
      confirm: true
      unsafe: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install curl
      apt:
        name: 
          - curl
          - ifupdown2
        state: present
        update_cache: true

    - name: Get IP address of current machine
      command: hostname -I
      register: ipaddress

    - name: Get hostname of current machine
      command: cat /etc/hostname
      register: hostname

    - name: Append /etc/hosts with current machine IP address
      shell: echo "127.0.0.1 \t localhost \n{{ ipaddress.stdout }} \t {{ hostname.stdout }}" > /etc/hosts

    - name: Restart Hostnamed Service
      systemd:
        name: systemd-hostnamed
        state: restarted

    - name: Change root user password
      user:
        name: root
        password: "{{ new_root_password_encrypted }}"

    - name: Add Proxmox Port Repositories
      shell:
        curl -L https://mirrors.apqa.cn/proxmox/debian/pveport.gpg | tee /usr/share/keyrings/pveport.gpg >/dev/null

    - name: Add Proxmox Port to sources list
      shell:
        echo "deb [arch=arm64 signed-by=/usr/share/keyrings/pveport.gpg] https://mirrors.apqa.cn/proxmox/debian/pve bookworm port" | tee /etc/apt/sources.list.d/pveport.list

    - name: Update Repositories
      apt: 
        update_cache: yes
        cache_valid_time: 86400
    
    - name: Install Proxmox VE
      apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
          - pve-edk2-firmware-aarch64
        state: present

    - name: Proxmox installed
      debug:
        msg: Proxmox was successfully installed
