---
- name: Apply config on Control Plane 1
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure -n {{ controlplane_1 }} --file {{ config_directory }}/controlplane.yaml
  changed_when: true

- name: Apply config on Control Plane 2
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure -n {{ controlplane_2 }} --file {{ config_directory }}/controlplane.yaml
  changed_when: true

- name: Apply config on Control Plane 3
  ansible.builtin.command:
    cmd: talosctl apply-config --insecure -n {{ controlplane_3 }} --file {{ config_directory }}/controlplane.yaml
  changed_when: true